---
name: Lazy Octopus Action
description: Create Release in Octopus
inputs:
  default_branch:
    description: Default/Main Branch Name
    required: false
    default: master
  deploy_package_version:
    default: "0.1.0.208"
  task_runner_version:
    default: "0.2.0-0.1.0-adding-devops-sp0001.118"
runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: ${{ github.action_path }}/start.ps1
      env:
        INPUT_DEFAULT_BRANCH: ${{ inputs.default_branch }}
        INPUT_DEPLOY_PACKAGE_VERSION: ${{ inputs.deploy_package_version }}
        INPUT_TASK_RUNNER_VERSION: ${{ inputs.task_runner_version }}
