---
name: Lazy Octopus Action
description: Create Release in Octopus
inputs:
  deploy_package_version:
    default: 1.1.1.663
    description: terraform-variant-apps package version
    required: false
  task_runner_version:
    description: cake-runner package version
    required: false
runs:
  using: composite
  steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
    - name: Set Default Branch
      shell: bash
      run: |
        if [ "$GitVersion_PreReleaseLabel" == "" ]; then
          echo "INPUT_DEFAULT_BRANCH=$GITVERSION_BRANCHNAME" >>"$GITHUB_ENV"
        fi
    - name: Setup Octopus Project & Release
      shell: pwsh
      run: ${{ github.action_path }}/tasks.ps1
      env:
        INPUT_DEPLOY_PACKAGE_VERSION: ${{ inputs.deploy_package_version }}
        TASK_RUNNER_VERSION: ${{ inputs.task_runner_version }}
        OCTOPUS_CLI_API_KEY: ${{ env.OCTOPUS_CLI_API_KEY }}
        OCTOPUS_CLI_SERVER: ${{ env.OCTOPUS_CLI_SERVER }}
    - name: Create Release Action
      uses: variant-inc/actions-collection/create-release-tag@v2
