---
name: Lazy Octopus Action
description: Create Release in Octopus
inputs:
  default_branch:
    description: Default/Main Branch Name
    required: false
    default: master
  deploy_scripts_path:
    description: >
      Path to the deploy scripts which is packaged
      and pushed to Octopus. This folder will contains the
      necessary scripts/helm charts/other misc to run the deployments
    required: false
    default: "."
  project_name:
    description: Name of the project name in Octopus
    required: true
  version:
    description: >
      Semantic Version that is used for determining
      the package and release version
    required: true
  space_name:
    description: >
      Name of the Space in Octopus. Usually, this will be Engineering,
      Mobile, DevOps, etc.
    required: true
runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: ${{ github.action_path }}/entrypoint.ps1
      env:
        DEFAULT_BRANCH: ${{ inputs.default_branch }}
        DEPLOY_SCRIPTS_PATH: ${{ inputs.deploy_scripts_path }}
        PROJECT_NAME: ${{ inputs.project_name }}
        VERSION: ${{ inputs.version }}
        SPACE_NAME: ${{ inputs.space_name }}
