---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{{{ .Release.Name }}}}-replicator
  labels:
    app: {{{{ include "chart.fullname" . }}}}
    {{{{- include "chart.labels" . | nindent 4 }}}}
data:
  octopus_space: {0}
  octopus_project: {1}
  github_repository: {2}
  github_user: {3}
  release_version: {4}
  image_name: {5}